### ISSUE TITLE
Getting an Error when opening the LoLVRSpectate.exe

### ISSUE THREAD

**Issue by Swoop0717** [Fire-Proof/LoLVRSpectate#8]
First of all I'm a programming Noob so please excuse me if I'm making an obvious mistake. I'm running Vorpx and Steam VR but when I try to open the LoLVRSpectate.exe I'm getting this message:

Windows platform        = Windows-8-6.2.9200
System Arch             = 64 bit
Python version  = 3.5.0 (v3.5.0:374f501f4567, Sep 13 2015, 02:16:59) [MSC v.1900 32 bit (Intel)]
True
Starting main loop
opening process b'League of Legends' ...

Traceback (most recent call last):
  File "<string>", line 14, in main
  File "C:\Users\nicko\Google Drev\ViveSpectate\LoLVRSpectate\main.py", line 14, in **init**
  File "C:\Users\nicko\Google Drev\ViveSpectate\LoLVRSpectate\LeagueOfLegends.py", line 6, in **init**
  File "C:\Users\nicko\Google Drev\ViveSpectate\LoLVRSpectate\memorpy\MemWorker.py", line 35, in **init**
  File "C:\Users\nicko\Google Drev\ViveSpectate\LoLVRSpectate\memorpy\Process.py", line 110, in open_debug_from_name
  File "C:\Users\nicko\Google Drev\ViveSpectate\LoLVRSpectate\memorpy\Process.py", line 115, in open_debug
pywintypes.error: (6, 'SetSecurityInfo', 'Das Handle ist ungültig.')
Press enter to close the program

Any ideas how to solve the problem?

**Comment by nickolaj-jepsen** [comment]
Are you running LoL as admin? if you are, you might need to run LoLVRSpectate.exe as admin as well.
I have just released a new version which should notify you, if you aren't running the program at the right privilege level
