### ISSUE TITLE
new issue..

### ISSUE THREAD

**Issue by Swoop0717** [Fire-Proof/LoLVRSpectate#9]
So this is the exact way I tried to get it working:
I opened LoL (as admin) -> started Vorpx (the LoLVRSpectate.exe is added to the excluded programs) -> started SteamVR -> started spectating a friends game. So the normal spectator view was displayed in the Vive. Next up when I started LoLVRSpectate (it told me everything was running just fine), the gameplay didn't move on and kind of froze still displayed in 2D.
I also tried a bunch of other methods but I always ended up having the same result or running it perfectly but not in VR :(
Am I doing something wrong or is this just a general bug? Thanks for the fast response last time.

**Comment by nickolaj-jepsen** [comment]
I assume that you are using the newest version (0.2.2), could you please post the LoLVRSpectate.log file which should be created in the same folder as the .exe

**Comment by Swoop0717** [comment]
2016-08-18 18:13:49,775 || Win platform = Windows-8-6.2.9200
2016-08-18 18:13:49,775 || System Arch = 64 bit
2016-08-18 18:13:49,775 || Python version = 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:43:06) [MSC v.1600 32 bit (Intel)]
2016-08-18 18:13:49,776 || VorpX exclusion = False
2016-08-18 18:13:49,776 || Starting main loop
2016-08-18 18:13:51,576 || opening process b'League of Legends' ...
2016-08-18 18:13:52,000 || tracking_fps: 070, controllers: 2
2016-08-18 18:13:53,004 || tracking_fps: 179, controllers: 2
2016-08-18 18:13:54,002 || tracking_fps: 178, controllers: 2
2016-08-18 18:13:55,000 || tracking_fps: 178, controllers: 2
2016-08-18 18:13:56,004 || tracking_fps: 179, controllers: 2
2016-08-18 18:13:56,876 || exception: access violation reading 0x00000000
Traceback (most recent call last):
  File "LoLVRSpectate\main.py", line 25, in run
  File "LoLVRSpectate\Spectate.py", line 78, in run
  File "LoLVRSpectate\Spectate.py", line 44, in _next_frame
  File "LoLVRSpectate\OpenVR.py", line 328, in controller_frame
  File "LoLVRSpectate\OpenVR.py", line 231, in __init__
  File "LoLVRSpectate\OpenVR.py", line 231, in <listcomp>
  File "LoLVRSpectate\OpenVR.py", line 185, in position
  File "site-packages\openvr__init__.py", line 1724, in getDeviceToAbsoluteTrackingPose
OSError: exception: access violation reading 0x00000000

**Comment by nickolaj-jepsen** [comment]
Sorry for the late response, i can't seem to recreate this issue, but i see two possible issue that might cause this. Either you have to run steam as admin, or it might be an issue with some antivirus software, you can try to disable it while running the .exe

**Comment by Swoop0717** [comment]
Thanks for all the effort :)
I'll try my best!
